ALTER TABLE ALRT_REF_TBL
 DROP PRIMARY KEY CASCADE;

DROP TABLE ALRT_REF_TBL CASCADE CONSTRAINTS;

CREATE TABLE ALRT_REF_TBL
(
  ALRT_KEY     NUMBER                           NOT NULL,
  ALRT_CD      VARCHAR2(5 BYTE)                 NOT NULL,
  ALRT_DESC    VARCHAR2(500 BYTE),
  ALRT_SUBJ    VARCHAR2(500 BYTE),
  ALRT_MSG     VARCHAR2(4000 BYTE),
  ALRT_RCPNT   VARCHAR2(4000 BYTE),
  AUDT_INS_DT  TIMESTAMP(6),
  AUDT_UPD_DT  TIMESTAMP(6),
  COL_META     VARCHAR2(4000 BYTE)
);


CREATE UNIQUE INDEX ALRT_REF_TBL_PK ON ALRT_REF_TBL
(ALRT_KEY)
NOLOGGING
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE ALRT_REF_TBL ADD (
  CONSTRAINT ALRT_REF_TBL_PK
  PRIMARY KEY
  (ALRT_KEY)
  USING INDEX ALRT_REF_TBL_PK
  ENABLE VALIDATE);
